package dev.henrique.inventory;
import dev.henrique.inventory.api.ApiModels.ReservationLineRequest; import dev.henrique.inventory.domain.*; import dev.henrique.inventory.repository.*; import dev.henrique.inventory.service.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.*; import java.util.*; import java.util.concurrent.*; import static org.assertj.core.api.Assertions.*;
@SpringBootTest @Testcontainers class PostgresIntegrationTest {
 @Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);}
 @Autowired ProductRepository products; @Autowired InventoryRepository inventory; @Autowired InventoryService inventoryService; @Autowired ReservationService reservations;
 @BeforeEach void clean(){inventory.deleteAll();}
 private Product stocked(int q){Product p=products.save(new Product("SKU-"+UUID.randomUUID(),"Widget"));inventoryService.set(p.getId(),q);return p;}
 @Test void reservationDecrementsInventoryAndCanBeConfirmed(){Product p=stocked(5);Reservation r=reservations.create(List.of(new ReservationLineRequest(p.getId(),4)));assertThat(inventoryService.get(p.getId()).getAvailableQuantity()).isOne();assertThat(reservations.transition(r.getId(),ReservationStatus.CONFIRMED).getStatus()).isEqualTo(ReservationStatus.CONFIRMED);}
 @Test void insufficientInventoryRollsBackAllMutations(){Product a=stocked(5),b=stocked(1);assertThatThrownBy(()->reservations.create(List.of(new ReservationLineRequest(a.getId(),4),new ReservationLineRequest(b.getId(),2)))).isInstanceOf(InsufficientInventoryException.class);assertThat(inventoryService.get(a.getId()).getAvailableQuantity()).isEqualTo(5);}
 @Test void cancellationReleasesStockAndIllegalTransitionIsRejected(){Product p=stocked(5);Reservation r=reservations.create(List.of(new ReservationLineRequest(p.getId(),4)));assertThat(reservations.transition(r.getId(),ReservationStatus.CANCELLED).getStatus()).isEqualTo(ReservationStatus.CANCELLED);assertThat(inventoryService.get(p.getId()).getAvailableQuantity()).isEqualTo(5);assertThatThrownBy(()->reservations.transition(r.getId(),ReservationStatus.CONFIRMED)).isInstanceOf(InvalidTransitionException.class);}
 @Test void twoConcurrentReservationsCannotOversell() throws Exception {Product p=stocked(5);ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);Callable<Boolean> task=()->{ready.countDown();start.await();try{reservations.create(List.of(new ReservationLineRequest(p.getId(),4)));return true;}catch(InsufficientInventoryException e){return false;}};Future<Boolean> a=pool.submit(task),b=pool.submit(task);ready.await(5,TimeUnit.SECONDS);start.countDown();List<Boolean> result=List.of(a.get(10,TimeUnit.SECONDS),b.get(10,TimeUnit.SECONDS));pool.shutdownNow();assertThat(result).containsExactlyInAnyOrder(true,false);assertThat(inventoryService.get(p.getId()).getAvailableQuantity()).isEqualTo(1);}
 @Test void databaseConstraintRejectsNegativeInventory(){Product p=products.save(new Product("SKU-"+UUID.randomUUID(),"Widget"));assertThatThrownBy(()->inventoryService.set(p.getId(),-1)).isInstanceOf(IllegalArgumentException.class);}
 @Test void unknownResourcesFailClearly(){UUID id=UUID.randomUUID();assertThatThrownBy(()->inventoryService.get(id)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->reservations.get(id)).isInstanceOf(ResourceNotFoundException.class);}
}
